# Generated by Django 4.2.2 on 2023-06-16 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Receptionist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            (
                                "Anesthesia & ICU Department",
                                "Anesthesia & ICU Department",
                            ),
                            ("Behavioral Medicine", "Behavioral Medicine"),
                            ("Child Health", "Child Health"),
                            ("Clinical Physiology", "Clinical Physiology"),
                            (
                                "Dental & Maxillofacial Surgery",
                                "Dental & Maxillofacial Surgery",
                            ),
                            ("Emergency Medicine", "Emergency Medicine"),
                            (
                                "Family Medicine & Public Health",
                                "Family Medicine & Public Health",
                            ),
                            ("Genetics Department", "Genetics Department"),
                        ],
                        default="",
                        max_length=100,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Nurse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            (
                                "Anesthesia & ICU Department",
                                "Anesthesia & ICU Department",
                            ),
                            ("Behavioral Medicine", "Behavioral Medicine"),
                            ("Child Health", "Child Health"),
                            ("Clinical Physiology", "Clinical Physiology"),
                            (
                                "Dental & Maxillofacial Surgery",
                                "Dental & Maxillofacial Surgery",
                            ),
                            ("Emergency Medicine", "Emergency Medicine"),
                            (
                                "Family Medicine & Public Health",
                                "Family Medicine & Public Health",
                            ),
                            ("Genetics Department", "Genetics Department"),
                        ],
                        default="",
                        max_length=100,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            (
                                "Anesthesia & ICU Department",
                                "Anesthesia & ICU Department",
                            ),
                            ("Behavioral Medicine", "Behavioral Medicine"),
                            ("Child Health", "Child Health"),
                            ("Clinical Physiology", "Clinical Physiology"),
                            (
                                "Dental & Maxillofacial Surgery",
                                "Dental & Maxillofacial Surgery",
                            ),
                            ("Emergency Medicine", "Emergency Medicine"),
                            (
                                "Family Medicine & Public Health",
                                "Family Medicine & Public Health",
                            ),
                            ("Genetics Department", "Genetics Department"),
                        ],
                        default="",
                        max_length=100,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
