# Generated by Django 4.1.3 on 2023-06-17 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_receptionist_nurse_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.CharField(choices=[('Anesthesia & ICU Department', 'Anesthesia & ICU Department'), ('Behavioral Medicine', 'Behavioral Medicine'), ('Child Health', 'Child Health'), ('Clinical Physiology', 'Clinical Physiology'), ('Dental & Maxillofacial Surgery', 'Dental & Maxillofacial Surgery'), ('Emergency Medicine', 'Emergency Medicine'), ('Family Medicine & Public Health', 'Family Medicine & Public Health'), ('Genetics Department', 'Genetics Department')], default='l[', max_length=35),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Doctor', 'Doctor'), ('Nurse', 'Nurse'), ('Receptionist', 'Receptionist')], default='Doctor', max_length=15),
        ),
    ]
